name: peaceinapod
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  yaru: ^0.5.6
  provider: ^6.0.5
  shared_preferences: ^2.0.18
  http: ^0.13.5
  crypto: ^3.0.2
  encrypt: ^5.0.1
  cached_network_image: ^3.2.3
  just_audio: ^0.9.32
  sliding_up_panel: ^2.0.0+1
  just_audio_background: ^0.0.1-beta.9
  flutter_launcher_icons: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/peaceinapod_title_bg.png"
  min_sdk_android: 31 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/peaceinapod_title_bg.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/peaceinapod_title_bg.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/peaceinapod_title_bg.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
